#!/bin/sh

if [ -z "$2" ]; then
  echo "dns_update email password"
fi
for file in /etc/nginx/sites-available/*; do
  domain=${file##*/}
  dotcount=`echo "$domain" | tr -cd '.' | wc -c`
  if [ "$dotcount" = 1 ]; then
    echo $domain
    ./fdu record update $1 $2 $domain -t A
    ./fdu record update $1 $2 $domain -t A -n www
  fi
done
