#!/bin/sh

if [ -z "$1" ]; then
  echo "Please enter a website"
  exit
elif ! [ $(id -u) = 0 ]; then
  echo "Please run using sudo."
  exit
fi
file=`grep -rn -m 1 '/etc/nginx/sites-available/' -e "server_name $1"  | cut -d : -f 1`
line_number=`grep -rn -m 1 '/etc/nginx/sites-available/' -e "server_name $1"  | cut -d : -f 2`
echo $file;
if [ -z "$file" ]; then
  echo "Config not found."
  exit
fi

read -p "Running on port number: " port
read -p "Desired location (ex./api): " url
if [ -z "$url" ]; then
  url="/"
fi

sed -i "${line_number}i# Generated with backend create\n\
	location $url {\n\
		proxy_pass http://localhost:$port;\n\
		proxy_set_header X-Real-IP \$remote_addr;\n\
		proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\n\
		proxy_set_header Host \$http_host;\n\
		proxy_set_header X-NginX-Proxy true;\n\
		proxy_http_version 1.1;\n\
		proxy_set_header Upgrade \$http_upgrade;\n\
		proxy_set_header Connection 'upgrade';\n\
	}" $file
